version: '2'
services:
    portus-haproxy:
        image: x3-portus-haproxy
        build: .
        container_name : 'x3-portus-haproxy-p'
        hostname: registry-ha.dck.x3rus.com
        environment:
            - TERM=xterm
        external_links:
            - x3-portus-registry-p:dck-registry-host
            - x3-portus-web-p:dck-registry-web
        networks:
            - br-x3
 
networks:
    br-x3:
        external: true
